### ISSUE TITLE
Create a requirements.txt file for installation of required dependencies

### ISSUE THREAD

**Issue by bjoyce3** [CyVerse-learning-materials/cyverse_quickstart_template#2]
It is difficult to update written documentation (doubly so for written documentation to write written documentation). As such, the best practices with Python-based projects (aka 'the most pythonic way') is to define a text file containing packages required for installation. This text file is called 'requirements.txt' and can be invoked as `pip install requirements.txt`. 

Having a single file that is invoked for set up also allows us to update the requirements easily (from a single source) to build and submit CyVerse ReadtheDocs repositories.

Add:
Installs specified in the README
recommonmark

**Comment by JasonJWilliamsNY** [comment]
Fixed in 2.0 release
