### ISSUE TITLE
Specify how to automatically update preview html when building documentation

### ISSUE THREAD

**Issue by bjoyce3** [CyVerse-learning-materials/cyverse_quickstart_template#3]
Sphinx can be set to autobuild html as a preview rather than researchers running the command `make html` over and over. Having the autobuild really helps for formatting and trying more advanced options in restructuredtext.

I may have missed it in the documentation, but the series of commands to run autobuild should be included.

**Comment by JasonJWilliamsNY** [comment]
Fixed in 2.0 release
